<?php
/**
 * Title: Accordion: Deane Fund Grants
 * Slug: ixion-child/accordion-deane-fund-grants
 * Categories: accordion-deane-fund-grants, featured
 * Description: Style the accordion and table that renders current and past Deane Fund grants.
 * Keywords: featured, accordion, deane fund, deane fund grants
 * Viewport Width: 800
 */
?><!-- wp:accordion {"metadata":{"name":"Deane Fund Grant Projects Parent"},"className":"accordion-deane-fund-grants-table"} --><div role="group" class="wp-block-accordion accordion-deane-fund-grants-table"><!-- wp:accordion-item {"metadata":{"name":"Deane Fund Grant Projects Panel"}} --><div class="wp-block-accordion-item"><!-- wp:accordion-heading {"metadata":{"name":"Deane Fund Grant Project Awarded by Year"},"className":"accordion-heading-deane-fund-grants-table"} --><h3 class="wp-block-accordion-heading accordion-heading-deane-fund-grants-table"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title">Deane Fund Grant Projects</span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3><!-- /wp:accordion-heading --><!-- wp:accordion-panel {"metadata":{"name":"Dean Fund Awards - Accordion Panel"}} --><div role="region" class="wp-block-accordion-panel"><!-- wp:table {"className":"deane-fund-grants-table","metadata":{"name":"Dean Fund Awards Table"}} --><figure class="wp-block-table deane-fund-grants-table"><table><thead><tr><th>Award Year</th><th>Project Description</th></tr></thead><tbody><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr></tbody></table></figure><!-- /wp:table --></div><!-- /wp:accordion-panel --></div><!-- /wp:accordion-item --></div><!-- /wp:accordion -->