<?php
/**
 * Title: FAQ Accordion With Media Grid
 * Slug: ixion-child/faq-accordion-with-media-grid
 * Categories: faq-accordion-with-media-grid, featured
 * Description: Style the native WordPress accordion block to contain an Accordion Panel with a 2-column media grid (33%/67%) that can accept an image and text.
 * Keywords: featured, accordion, faq accordion, faq accordion media, media grid, faq-accordion-media, faq_accordion_media
 * Viewport Width: 800
 */
?><!-- wp:accordion {"iconPosition":"left","autoclose":true,"className":"faq-accordion"} --><div role="group" class="wp-block-accordion faq-accordion"><!-- wp:accordion-item {"className":"faq-accordion__item"} --><div class="wp-block-accordion-item faq-accordion__item"><!-- wp:accordion-heading {"iconPosition":"left"} --><h3 class="wp-block-accordion-heading"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span><span class="wp-block-accordion-heading__toggle-title"></span></button></h3><!-- /wp:accordion-heading --><!-- wp:accordion-panel {"className":"faq-accordion__media-panel"} --><div role="region" class="wp-block-accordion-panel faq-accordion__media-panel"><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column {"width":"33.33%","metadata":{"name":"Image Column"}} --><div class="wp-block-column" style="flex-basis:33.33%"><!-- wp:image --><figure class="wp-block-image"><img alt=""/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column {"width":"66.66%","metadata":{"name":"Text Column"}} --><div class="wp-block-column" style="flex-basis:66.66%"><!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li>Click here to write your first bullet point…Duplicate this list item to add another bullet<br>item below. Bullet items are styled by the Ixion-Child theme.</li><!-- /wp:list-item --></ul><!-- /wp:list --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:accordion-panel --></div><!-- /wp:accordion-item --></div><!-- /wp:accordion -->
