<?php
/**
 * Title: Full-Width 3-Column Circular Feature Trio
 * Slug: ixion-child/full-width-three-column-feature
 * Categories: full-width-three-column-feature, featured
 * Keywords: hero, three column, circle image, feature trio
 * Description: A full-bleed section containing 3 equal-width feature columns with circular cropped images, headings, and text.
 */
?><!-- wp:group {"tagName":"section","align":"full","className":"full-width-trio-section","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull full-width-trio-section"><!-- wp:columns {"align":"wide","className":"trio-columns"} --><div class="wp-block-columns alignwide trio-columns"><!-- wp:column {"className":"trio-card"} --><div class="wp-block-column trio-card"><!-- wp:image {"aspectRatio":"1","scale":"cover","sizeSlug":"medium","className":"is-style-rounded trio-image"} --><figure class="wp-block-image size-medium is-style-rounded trio-image"><img alt="" style="aspect-ratio:1;object-fit:cover"/></figure><!-- /wp:image --><!-- wp:heading {"level":3,"placeholder":"Feature Title One...","style":{"typography":{"textAlign":"center"}}} --><h3 class="wp-block-heading has-text-align-center"></h3><!-- /wp:heading --><!-- wp:paragraph {"placeholder":"Write description...","style":{"typography":{"textAlign":"center"}}} --><p class="has-text-align-center"></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"trio-card"} --><div class="wp-block-column trio-card"><!-- wp:image {"aspectRatio":"1","scale":"cover","sizeSlug":"medium","className":"is-style-rounded trio-image"} --><figure class="wp-block-image size-medium is-style-rounded trio-image"><img alt="" style="aspect-ratio:1;object-fit:cover"/></figure><!-- /wp:image --><!-- wp:heading {"level":3,"placeholder":"Feature Title Two...","style":{"typography":{"textAlign":"center"}}} --><h3 class="wp-block-heading has-text-align-center"></h3><!-- /wp:heading --><!-- wp:paragraph {"placeholder":"Write description...","style":{"typography":{"textAlign":"center"}}} --><p class="has-text-align-center"></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"className":"trio-card"} --><div class="wp-block-column trio-card"><!-- wp:image {"aspectRatio":"1","scale":"cover","sizeSlug":"medium","className":"is-style-rounded trio-image"} --><figure class="wp-block-image size-medium is-style-rounded trio-image"><img alt="" style="aspect-ratio:1;object-fit:cover"/></figure><!-- /wp:image --><!-- wp:heading {"level":3,"placeholder":"Feature Title Three...","style":{"typography":{"textAlign":"center"}}} --><h3 class="wp-block-heading has-text-align-center"></h3><!-- /wp:heading --><!-- wp:paragraph {"placeholder":"Write description...","style":{"typography":{"textAlign":"center"}}} --><p class="has-text-align-center"></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></section><!-- /wp:group -->
